import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { extractDocumentText } from '../src/documentText.js';

// Standard ZIP/DEFLATE fixtures generated by Python zipfile, independently of
// the reader. No platform-specific archive command is needed to run the tests.
const fixture = (name: string) => readFile(new URL(`./fixtures/${name}`, import.meta.url));

test('real ZIP/DOCX text extraction retains Chinese content and explicitly limits layout claims', async () => {
  const extracted = extractDocumentText(await fixture('document-text.zip'));
  assert.match(extracted.text, /中文需求 & 公式/); assert.match(extracted.text, /表格内容完整/);
  assert.match(extracted.coverage, /layout.*not proven/);
  assert.throws(() => extractDocumentText(Buffer.from('PK\x03\x04broken archive')), /ZIP/);
  const oversized = await fixture('oversized-text.zip');
  assert.throws(() => extractDocumentText(oversized), /oversized/);
  const combined = await fixture('combined-text.zip');
  assert.throws(() => extractDocumentText(combined), /Combined document text/);
});
